use axum::{
    Json, Router,
    extract::DefaultBodyLimit,
    extract::{Query, State},
    http::StatusCode,
    response::{IntoResponse, Response},
    routing::{get, post},
};
pub mod assistant;
pub mod embedding_document;
pub mod schematic_graph;
pub mod schematic_mcp;
use include_dir::{Dir, include_dir};
use serde::{Deserialize, Serialize};
use std::{
    collections::BTreeMap,
    fs,
    path::{Component, Path, PathBuf},
    sync::{
        Arc,
        atomic::{AtomicU64, Ordering},
    },
};
use thiserror::Error;
use tower_http::services::{ServeDir, ServeFile};
use walkdir::WalkDir;

const AGENTS_BEGIN: &str = "<!-- software-schematic:begin -->";
const AGENTS_END: &str = "<!-- software-schematic:end -->";
const AGENTS_GUIDANCE: &str = r#"<!-- software-schematic:begin -->
## Software Schematic development

Treat the project schematic graph as the source of software contracts. Before proposing or implementing a change, call the project-local `software_schematic` MCP server and resolve the request's natural language to a development root. Record the resolved root URN in the concise OpenSpec-style proposal. Do not duplicate detailed contracts in proposal or spec prose; put them in diagram Documentation.

Every implementation task must include `nodeRefs` containing the universal URNs of the diagram entities it changes. Only entities whose persisted Implementation Status is `new` (green) or `modify` (orange) are authorized for implementation. Use graph lookup and neighborhood tools to understand relationships and source citations.

Software Schematic MCP tools are query-only. Never mutate or refresh the graph, diagrams, Documentation, Implementation Status, or source contracts from Codex. If a contract is missing or incorrect, stop and ask the user to evaluate and save the change in the Software Schematic web application; a successful human-authored save refreshes the running graph.
<!-- software-schematic:end -->"#;

pub fn validate_package_name(value: &str) -> Result<&str> {
    if value.is_empty() || !value.split('.').all(is_lower_camel) {
        return Err(Error::Message("package Name must use dot-separated lowerCamelCase segments, for example cybling.subscription".into()));
    }
    Ok(value)
}

pub fn validate_process_name(value: &str) -> Result<&str> {
    if !is_upper_camel(value) {
        return Err(Error::Message(
            "process Name must use UpperCamelCase, for example SelectAndOutfit".into(),
        ));
    }
    Ok(value)
}

pub fn validate_member_name(value: &str) -> Result<&str> {
    if !is_lower_camel(value) {
        return Err(Error::Message(
            "task or event Name must use lowerCamelCase, for example processSubscription".into(),
        ));
    }
    Ok(value)
}

fn is_lower_camel(value: &str) -> bool {
    value.as_bytes().first().is_some_and(u8::is_ascii_lowercase)
        && value.bytes().all(|byte| byte.is_ascii_alphanumeric())
}

fn is_upper_camel(value: &str) -> bool {
    value.as_bytes().first().is_some_and(u8::is_ascii_uppercase)
        && value.bytes().all(|byte| byte.is_ascii_alphanumeric())
}

pub fn validate_qualified_process_name(value: &str) -> Result<&str> {
    let (package, process) = value.rsplit_once('.').ok_or_else(|| Error::Message(
        "qualified process Name must include a package and process, for example cybling.SelectAndOutfit".into(),
    ))?;
    validate_package_name(package)?;
    validate_process_name(process)?;
    Ok(value)
}

pub fn validate_element_name(value: &str) -> Result<&str> {
    let mut parts = value.split('#');
    let process = parts.next().unwrap_or_default();
    let member = parts.next();
    if parts.next().is_some() {
        return Err(Error::Message(
            "Name may contain only one # member separator".into(),
        ));
    }
    validate_qualified_process_name(process)?;
    if let Some(member) = member {
        validate_member_name(member)?;
    }
    Ok(value)
}

pub fn composition_folder_for_name(value: &str) -> Result<PathBuf> {
    validate_qualified_process_name(value)?;
    Ok(value.split('.').collect())
}

pub fn qualified_name_for_composition_folder(value: &Path) -> Result<String> {
    if value.is_absolute()
        || value
            .components()
            .any(|part| !matches!(part, Component::Normal(_)))
    {
        return Err(Error::Message(
            "composition folder must be confined beneath schematics".into(),
        ));
    }
    let mut parts = value
        .iter()
        .map(|part| {
            part.to_str()
                .ok_or_else(|| Error::Message("composition folder must be UTF-8".into()))
        })
        .collect::<Result<Vec<_>>>()?;
    if parts.last() == Some(&"main.bpmn") {
        parts.pop();
    }
    let name = parts.join(".");
    validate_qualified_process_name(&name)?;
    Ok(name)
}

pub fn symbol_collision_key(value: &str) -> String {
    value.to_ascii_lowercase()
}

// Release builds embed the production web bundle generated by software-schematic-web.
static WEB_ASSETS: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/assets/web");
static MODEL_ASSETS: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/assets/models");
const STARTER_BPMN: &str = include_str!("../assets/starter.bpmn");
const STARTER_CMMN: &str = include_str!("../assets/starter.cmmn");
const STARTER_MD: &str = include_str!("../assets/starter.md");
const PROJECT_LICENSE: &str = include_str!("../../LICENSE");
const PROJECT_NOTICE: &str = include_str!("../../NOTICE");
const THIRD_PARTY_NOTICES: &str = include_str!("../../THIRD_PARTY_NOTICES.md");
const MAC_WRAPPER: &str = "#!/bin/sh\nset -eu\nSCRIPT_DIR=$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\ncase \"${1:-}\" in\n  auth) shift; exec \"$SCRIPT_DIR/.ss/bin/ss\" auth --project \"$SCRIPT_DIR\" \"$@\" ;;\n  embeddings) shift; exec \"$SCRIPT_DIR/.ss/bin/ss\" embeddings --project \"$SCRIPT_DIR\" \"$@\" ;;\n  mcp) shift; exec \"$SCRIPT_DIR/.ss/bin/ss\" mcp --project \"$SCRIPT_DIR\" \"$@\" ;;\n  update) shift; exec \"$SCRIPT_DIR/.ss/bin/ss\" update --project \"$SCRIPT_DIR\" \"$@\" ;;\nesac\nexec \"$SCRIPT_DIR/.ss/bin/ss\" serve --project \"$SCRIPT_DIR\" \"$@\"\n";
const WINDOWS_WRAPPER: &str = "@echo off\r\nsetlocal\r\nif \"%~1\"==\"auth\" (\r\n  shift\r\n  \"%~dp0.ss\\bin\\ss.exe\" auth --project \"%~dp0\" %*\r\n) else if \"%~1\"==\"embeddings\" (\r\n  shift\r\n  \"%~dp0.ss\\bin\\ss.exe\" embeddings --project \"%~dp0\" %*\r\n) else if \"%~1\"==\"mcp\" (\r\n  shift\r\n  \"%~dp0.ss\\bin\\ss.exe\" mcp --project \"%~dp0\" %*\r\n) else if \"%~1\"==\"update\" (\r\n  shift\r\n  \"%~dp0.ss\\bin\\ss.exe\" update --project \"%~dp0\" %*\r\n) else (\r\n  \"%~dp0.ss\\bin\\ss.exe\" serve --project \"%~dp0\" %*\r\n)\r\n";

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Debug, Error)]
pub enum Error {
    #[error("{0}")]
    Message(String),
    #[error(transparent)]
    Io(#[from] std::io::Error),
    #[error(transparent)]
    WalkDir(#[from] walkdir::Error),
}

impl IntoResponse for Error {
    fn into_response(self) -> Response {
        let status = match self {
            Error::Message(_) => StatusCode::BAD_REQUEST,
            Error::Io(ref value) if value.kind() == std::io::ErrorKind::NotFound => {
                StatusCode::NOT_FOUND
            }
            _ => StatusCode::INTERNAL_SERVER_ERROR,
        };
        (
            status,
            Json(serde_json::json!({ "error": self.to_string() })),
        )
            .into_response()
    }
}

#[derive(Debug, Clone)]
pub struct ProjectLayout {
    pub project: PathBuf,
    pub tool: PathBuf,
    pub schematics: PathBuf,
}

pub fn init_project(project: impl AsRef<Path>) -> Result<ProjectLayout> {
    let project = absolute(project.as_ref())?;
    fs::create_dir_all(&project)?;
    let collisions: Vec<_> = [".ss", "schematics", "ssw", "ssw.cmd"]
        .into_iter()
        .map(|name| project.join(name))
        .filter(|path| path.exists())
        .collect();
    if !collisions.is_empty() {
        return Err(Error::Message(format!(
            "initialization refused; path already exists: {}",
            collisions
                .iter()
                .map(|p| p.display().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        )));
    }

    let tool = project.join(".ss");
    let web = tool.join("web");
    let schematics = project.join("schematics");
    fs::create_dir_all(tool.join("bin"))?;
    fs::create_dir_all(&web)?;
    fs::create_dir_all(&schematics)?;
    WEB_ASSETS
        .extract(&web)
        .map_err(|e| Error::Message(e.to_string()))?;
    MODEL_ASSETS
        .extract(tool.join("models"))
        .map_err(|e| Error::Message(e.to_string()))?;
    fs::write(
        tool.join("version"),
        format!("{}\n", env!("CARGO_PKG_VERSION")),
    )?;
    fs::write(
        tool.join("operation-plan.schema.json"),
        serde_json::to_vec_pretty(&assistant::operation_plan_schema()).unwrap(),
    )?;
    fs::write(tool.join("starter.cmmn"), STARTER_CMMN)?;
    fs::write(tool.join("LICENSE"), PROJECT_LICENSE)?;
    fs::write(tool.join("NOTICE"), PROJECT_NOTICE)?;
    fs::write(tool.join("THIRD_PARTY_NOTICES.md"), THIRD_PARTY_NOTICES)?;
    fs::write(schematics.join("main.cmmn"), STARTER_CMMN)?;
    fs::write(schematics.join("main.md"), STARTER_MD)?;
    fs::write(project.join("ssw"), MAC_WRAPPER)?;
    fs::write(project.join("ssw.cmd"), WINDOWS_WRAPPER)?;
    write_project_id(&tool, &project)?;
    update_managed_project_files(&project)?;

    let current_exe = std::env::current_exe()?;
    let runtime_name = if cfg!(windows) { "ss.exe" } else { "ss" };
    fs::copy(current_exe, tool.join("bin").join(runtime_name))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(project.join("ssw"), fs::Permissions::from_mode(0o755))?;
        fs::set_permissions(
            tool.join("bin").join(runtime_name),
            fs::Permissions::from_mode(0o755),
        )?;
    }
    Ok(ProjectLayout {
        project,
        tool,
        schematics,
    })
}

pub fn update_project(project: impl AsRef<Path>) -> Result<ProjectLayout> {
    let project = absolute(project.as_ref())?;
    let tool = project.join(".ss");
    let schematics = project.join("schematics");
    if !tool.is_dir() || !schematics.join("main.cmmn").is_file() {
        return Err(Error::Message(
            "not a Software Schematic project; expected .ss and schematics/main.cmmn".into(),
        ));
    }
    fs::create_dir_all(tool.join("bin"))?;
    fs::create_dir_all(tool.join("web"))?;
    WEB_ASSETS
        .extract(tool.join("web"))
        .map_err(|e| Error::Message(e.to_string()))?;
    MODEL_ASSETS
        .extract(tool.join("models"))
        .map_err(|e| Error::Message(e.to_string()))?;
    fs::write(
        tool.join("version"),
        format!("{}\n", env!("CARGO_PKG_VERSION")),
    )?;
    fs::write(
        tool.join("operation-plan.schema.json"),
        serde_json::to_vec_pretty(&assistant::operation_plan_schema()).unwrap(),
    )?;
    fs::write(tool.join("LICENSE"), PROJECT_LICENSE)?;
    fs::write(tool.join("NOTICE"), PROJECT_NOTICE)?;
    fs::write(tool.join("THIRD_PARTY_NOTICES.md"), THIRD_PARTY_NOTICES)?;
    fs::write(project.join("ssw"), MAC_WRAPPER)?;
    fs::write(project.join("ssw.cmd"), WINDOWS_WRAPPER)?;
    write_project_id(&tool, &project)?;
    update_managed_project_files(&project)?;
    let current_exe = std::env::current_exe()?;
    let runtime_name = if cfg!(windows) { "ss.exe" } else { "ss" };
    fs::copy(current_exe, tool.join("bin").join(runtime_name))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(project.join("ssw"), fs::Permissions::from_mode(0o755))?;
        fs::set_permissions(
            tool.join("bin").join(runtime_name),
            fs::Permissions::from_mode(0o755),
        )?;
    }
    Ok(ProjectLayout {
        project,
        tool,
        schematics,
    })
}

fn write_project_id(tool: &Path, project: &Path) -> Result<()> {
    let path = tool.join("project-id");
    if path.exists() {
        return Ok(());
    }
    use sha2::{Digest, Sha256};
    let seed = format!(
        "{}\0{}",
        project
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("project"),
        project.display()
    );
    let digest = format!("{:x}", Sha256::digest(seed.as_bytes()));
    fs::write(path, format!("{}\n", &digest[..24]))?;
    Ok(())
}

fn update_managed_project_files(project: &Path) -> Result<()> {
    update_agents(project)?;
    update_codex_config(project)
}

fn update_agents(project: &Path) -> Result<()> {
    let path = project.join("AGENTS.md");
    let existing = fs::read_to_string(&path).unwrap_or_default();
    let eol = if existing.contains("\r\n") {
        "\r\n"
    } else {
        "\n"
    };
    let block = AGENTS_GUIDANCE.replace('\n', eol);
    let updated = match (existing.find(AGENTS_BEGIN), existing.find(AGENTS_END)) {
        (Some(start), Some(end)) if start <= end => {
            let tail = end + AGENTS_END.len();
            format!("{}{}{}", &existing[..start], block, &existing[tail..])
        }
        (None, None) if existing.is_empty() => format!("{block}{eol}"),
        (None, None) => format!(
            "{}{eol}{eol}{block}{eol}",
            existing.trim_end_matches(['\r', '\n'])
        ),
        _ => {
            return Err(Error::Message(
                "AGENTS.md contains an incomplete Software Schematic managed block".into(),
            ));
        }
    };
    fs::write(path, updated)?;
    Ok(())
}

fn update_codex_config(project: &Path) -> Result<()> {
    use toml_edit::{DocumentMut, Item, Table, Value};
    let directory = project.join(".codex");
    fs::create_dir_all(&directory)?;
    let path = directory.join("config.toml");
    let source = fs::read_to_string(&path).unwrap_or_default();
    let mut document = source
        .parse::<DocumentMut>()
        .map_err(|e| Error::Message(format!("invalid .codex/config.toml: {e}")))?;
    if !document.as_table().contains_key("mcp_servers") {
        document["mcp_servers"] = Item::Table(Table::new());
    }
    document["mcp_servers"]["software_schematic"]["command"] = Item::Value(Value::from("./ssw"));
    document["mcp_servers"]["software_schematic"]["args"] =
        toml_edit::value(toml_edit::Array::from_iter(["mcp"]));
    fs::write(path, document.to_string())?;
    Ok(())
}

fn absolute(path: &Path) -> Result<PathBuf> {
    if path.is_absolute() {
        Ok(path.to_path_buf())
    } else {
        Ok(std::env::current_dir()?.join(path))
    }
}

#[derive(Debug, Clone, Deserialize, Serialize)]
struct AssistantProjectConfig {
    provider: String,
}

fn assistant_config_path(project: &Path) -> PathBuf {
    project.join(".ss/assistant.json")
}

fn command_available(command: &str) -> bool {
    std::process::Command::new(command)
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .is_ok_and(|status| status.success())
}

fn configured_assistant_provider(project: &Path) -> Option<String> {
    fs::read(assistant_config_path(project))
        .ok()
        .and_then(|content| serde_json::from_slice::<AssistantProjectConfig>(&content).ok())
        .map(|config| config.provider)
}

fn resolved_assistant_provider(project: &Path) -> Option<String> {
    std::env::var("SSW_ASSISTANT_PROVIDER")
        .ok()
        .or_else(|| configured_assistant_provider(project))
        .or_else(|| command_available("codex").then(|| "codex".into()))
        .or_else(|| command_available("claude").then(|| "claude".into()))
}

pub fn assistant_auth_login(project: impl AsRef<Path>, requested: Option<&str>) -> Result<()> {
    let project = absolute(project.as_ref())?.canonicalize()?;
    let provider = match requested {
        Some("codex") if command_available("codex") => "codex",
        Some("claude") if command_available("claude") => "claude",
        Some("codex" | "claude") => {
            return Err(Error::Message(format!(
                "{} CLI is not installed or not available on PATH",
                requested.unwrap()
            )));
        }
        Some(other) => {
            return Err(Error::Message(format!(
                "unsupported assistant provider: {other}"
            )));
        }
        None if command_available("codex") => "codex",
        None if command_available("claude") => "claude",
        None => {
            return Err(Error::Message(
                "install Codex CLI or Claude Code before running assistant login".into(),
            ));
        }
    };
    println!(
        "Opening the official {provider} sign-in flow. SSW never receives your password or token."
    );
    let status = if provider == "codex" {
        std::process::Command::new("codex").arg("login").status()?
    } else {
        std::process::Command::new("claude")
            .args(["auth", "login"])
            .status()?
    };
    if !status.success() {
        return Err(Error::Message(format!(
            "{provider} sign-in did not complete"
        )));
    }
    let path = assistant_config_path(&project);
    fs::create_dir_all(path.parent().unwrap())?;
    fs::write(
        path,
        serde_json::to_vec_pretty(&AssistantProjectConfig {
            provider: provider.into(),
        })
        .unwrap(),
    )?;
    println!("Software Schematic assistant configured to use {provider} for this project.");
    Ok(())
}

pub fn assistant_auth_status(project: impl AsRef<Path>) -> Result<()> {
    let project = absolute(project.as_ref())?.canonicalize()?;
    let Some(provider) = configured_assistant_provider(&project) else {
        println!("No local assistant is configured. Run ./ssw auth login.");
        return Ok(());
    };
    let status = if provider == "codex" {
        std::process::Command::new("codex")
            .args(["login", "status"])
            .status()?
    } else {
        std::process::Command::new("claude")
            .args(["auth", "status"])
            .status()?
    };
    if !status.success() {
        return Err(Error::Message(format!(
            "{provider} is configured but not authenticated"
        )));
    }
    println!("Project assistant provider: {provider}");
    Ok(())
}

pub fn assistant_auth_logout(project: impl AsRef<Path>) -> Result<()> {
    let project = absolute(project.as_ref())?.canonicalize()?;
    let Some(provider) = configured_assistant_provider(&project) else {
        return Err(Error::Message(
            "no project assistant provider is configured".into(),
        ));
    };
    let status = if provider == "codex" {
        std::process::Command::new("codex").arg("logout").status()?
    } else {
        std::process::Command::new("claude")
            .args(["auth", "logout"])
            .status()?
    };
    if !status.success() {
        return Err(Error::Message(format!(
            "{provider} logout did not complete"
        )));
    }
    let path = assistant_config_path(&project);
    if path.exists() {
        fs::remove_file(path)?;
    }
    println!("Signed out of {provider} and removed the project assistant selection.");
    Ok(())
}

#[derive(Clone)]
pub struct AppState {
    project: Arc<PathBuf>,
    schematics: Arc<PathBuf>,
    assistant_slots: Arc<tokio::sync::Semaphore>,
    embedding_jobs: Arc<tokio::sync::Mutex<BTreeMap<String, u64>>>,
    embedding_generation: Arc<AtomicU64>,
    embedding_slots: Arc<tokio::sync::Semaphore>,
    embedding_status: Arc<tokio::sync::RwLock<EmbeddingOutcome>>,
}

impl AppState {
    pub fn new(project: impl AsRef<Path>) -> Result<Self> {
        let project = absolute(project.as_ref())?.canonicalize()?;
        let schematics = project.join("schematics").canonicalize()?;
        Ok(Self {
            project: Arc::new(project),
            schematics: Arc::new(schematics),
            assistant_slots: Arc::new(tokio::sync::Semaphore::new(2)),
            embedding_jobs: Arc::new(tokio::sync::Mutex::new(BTreeMap::new())),
            embedding_generation: Arc::new(AtomicU64::new(0)),
            embedding_slots: Arc::new(tokio::sync::Semaphore::new(1)),
            embedding_status: Arc::new(tokio::sync::RwLock::new(EmbeddingOutcome::default())),
        })
    }

    pub fn resolve(&self, relative: &str, permit_missing: bool) -> Result<PathBuf> {
        let path = Path::new(relative);
        if relative.is_empty()
            || path.is_absolute()
            || path
                .components()
                .any(|c| !matches!(c, Component::Normal(_)))
        {
            return Err(Error::Message(
                "path must be a normalized path relative to schematics".into(),
            ));
        }
        let candidate = self.schematics.join(path);
        let mut existing = candidate.as_path();
        while !existing.exists() {
            existing = existing
                .parent()
                .ok_or_else(|| Error::Message("path has no confined ancestor".into()))?;
        }
        let canonical_ancestor = existing.canonicalize()?;
        if !canonical_ancestor.starts_with(self.schematics.as_path()) {
            return Err(Error::Message("path escapes schematics".into()));
        }
        if !permit_missing && !candidate.exists() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                format!("{} not found", relative),
            )
            .into());
        }
        if candidate.exists()
            && !candidate
                .canonicalize()?
                .starts_with(self.schematics.as_path())
        {
            return Err(Error::Message("path escapes schematics".into()));
        }
        Ok(candidate)
    }

    pub fn project_name(&self) -> Result<String> {
        self.project
            .file_name()
            .and_then(|value| value.to_str())
            .filter(|value| !value.is_empty())
            .map(str::to_owned)
            .ok_or_else(|| Error::Message("project directory has no usable name".into()))
    }
}

#[derive(Deserialize)]
struct PathQuery {
    path: String,
}

#[derive(Deserialize)]
struct WriteRequest {
    path: String,
    content: String,
    revision: u64,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct WriteResponse {
    path: String,
    revision: u64,
    graph_refresh: schematic_mcp::GraphRefreshOutcome,
    embedding: EmbeddingOutcome,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct EmbeddingOutcome {
    status: String,
    path: Option<String>,
    body_hash: Option<String>,
    diagnostic: Option<String>,
}

impl Default for EmbeddingOutcome {
    fn default() -> Self {
        Self {
            status: "current".into(),
            path: None,
            body_hash: None,
            diagnostic: None,
        }
    }
}

#[derive(Deserialize)]
struct RenameRequest {
    diagram_path: String,
    old_id: String,
    new_id: String,
}

#[derive(Deserialize)]
struct CompositionRequest {
    #[serde(default = "default_composition_kind")]
    kind: String,
    qualified_name: Option<String>,
    package_name: Option<String>,
}

fn default_composition_kind() -> String {
    "bpmn".into()
}

#[derive(Serialize)]
struct CompositionResponse {
    name: String,
    diagram: String,
    documentation: String,
    created: bool,
}

#[derive(Debug, Deserialize)]
struct ProcessRenameRequest {
    old_qualified_name: String,
    new_qualified_name: String,
}

#[derive(Debug, Deserialize)]
struct PackageRenameRequest {
    old_package_name: String,
    new_package_name: String,
}

#[derive(Serialize)]
struct ProjectMetadata {
    name: String,
    assistant_provider: Option<String>,
}

pub fn app(state: AppState) -> Router {
    let web = state.project.join(".ss/web");
    Router::new()
        .route("/api/project", get(project_metadata))
        .route("/api/diagrams", get(list_diagrams))
        .route("/api/file", get(read_file).put(write_file))
        .route("/api/graph-refresh", get(graph_refresh_status))
        .route("/api/embedding-status", get(embedding_status))
        .route("/api/rename-documentation", post(rename_documentation))
        .route("/api/compositions", post(resolve_composition))
        .route("/api/process-renames", post(rename_process))
        .route("/api/package-renames", post(rename_package))
        .route(
            "/api/assistant/proposals",
            post(assistant_proposal).layer(DefaultBodyLimit::max(512 * 1024)),
        )
        .fallback_service(
            ServeDir::new(&web).not_found_service(ServeFile::new(web.join("index.html"))),
        )
        .with_state(state)
}

async fn assistant_proposal(
    State(state): State<AppState>,
    Json(request): Json<assistant::AssistantRequest>,
) -> Result<Json<assistant::AssistantResult>> {
    let _permit = state
        .assistant_slots
        .clone()
        .try_acquire_owned()
        .map_err(|_| {
            Error::Message(
                "assistant request limit reached; wait for an active request to finish".into(),
            )
        })?;
    let result = tokio::time::timeout(
        std::time::Duration::from_secs(30),
        assistant::generate(
            &request,
            state.project.as_ref().clone(),
            resolved_assistant_provider(state.project.as_path()),
        ),
    )
    .await
    .map_err(|_| Error::Message("assistant provider timed out".into()))??;
    Ok(Json(result))
}

async fn project_metadata(State(state): State<AppState>) -> Result<Json<ProjectMetadata>> {
    Ok(Json(ProjectMetadata {
        name: state.project_name()?,
        assistant_provider: resolved_assistant_provider(state.project.as_path()),
    }))
}

pub async fn serve(project: PathBuf, open_browser: bool) -> Result<()> {
    let state = AppState::new(project)?;
    let backfill_state = state.clone();
    tokio::spawn(async move {
        let _ = schedule_project_embeddings(&backfill_state).await;
    });
    let listener = tokio::net::TcpListener::bind((std::net::Ipv4Addr::LOCALHOST, 0)).await?;
    let address = listener.local_addr()?;
    let url = format!("http://{address}");
    println!("Software Schematic is running at {url}");
    if open_browser {
        open::that(&url).map_err(|e| Error::Message(format!("could not open browser: {e}")))?;
    }
    axum::serve(listener, app(state))
        .with_graceful_shutdown(shutdown_signal())
        .await?;
    Ok(())
}

async fn shutdown_signal() {
    let ctrl_c = async {
        tokio::signal::ctrl_c()
            .await
            .expect("install Ctrl+C handler")
    };
    #[cfg(unix)]
    let terminate = async {
        tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
            .expect("install signal handler")
            .recv()
            .await;
    };
    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();
    tokio::select! { _ = ctrl_c => {}, _ = terminate => {} }
}

async fn list_diagrams(State(state): State<AppState>) -> Result<Json<Vec<String>>> {
    let mut diagrams = Vec::new();
    for entry in WalkDir::new(state.schematics.as_path()).follow_links(false) {
        let entry = entry?;
        if entry.file_type().is_file()
            && entry.path().extension().is_some_and(|ext| {
                ext.eq_ignore_ascii_case("bpmn") || ext.eq_ignore_ascii_case("cmmn")
            })
        {
            diagrams.push(
                entry
                    .path()
                    .strip_prefix(state.schematics.as_path())
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/"),
            );
        }
    }
    diagrams.sort();
    Ok(Json(diagrams))
}

async fn read_file(
    State(state): State<AppState>,
    Query(query): Query<PathQuery>,
) -> Result<String> {
    let path = state.resolve(&query.path, false)?;
    if !matches!(
        path.extension().and_then(|x| x.to_str()),
        Some("bpmn" | "cmmn" | "md")
    ) {
        return Err(Error::Message(
            "only BPMN, CMMN, and Markdown files are readable".into(),
        ));
    }
    let content = tokio::fs::read_to_string(path).await?;
    if query.path.ends_with(".md") {
        Ok(embedding_document::parse_markdown(&content).body)
    } else {
        Ok(content)
    }
}

async fn write_file(
    State(state): State<AppState>,
    Json(request): Json<WriteRequest>,
) -> Result<Json<WriteResponse>> {
    let path = state.resolve(&request.path, true)?;
    if !matches!(
        path.extension().and_then(|x| x.to_str()),
        Some("bpmn" | "cmmn" | "md")
    ) {
        return Err(Error::Message(
            "only BPMN, CMMN, and Markdown files are writable".into(),
        ));
    }
    let change_kind = if path.exists() {
        schematic_mcp::DocumentChangeKind::Replaced
    } else {
        schematic_mcp::DocumentChangeKind::Created
    };
    if let Some(parent) = path.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }
    let authored_content = if request.path.ends_with(".md") {
        embedding_document::parse_markdown(&request.content).body
    } else {
        request.content
    };
    atomic_write(&path, authored_content.as_bytes()).await?;
    let embedding = if request.path.ends_with(".md") {
        schedule_embedding(&state, request.path.clone(), authored_content).await
    } else {
        state.embedding_status.read().await.clone()
    };
    let graph_refresh = schematic_mcp::notify_documents_changed(
        state.project.as_path(),
        &request.path,
        change_kind,
    )
    .await;
    Ok(Json(WriteResponse {
        path: request.path,
        revision: request.revision,
        graph_refresh,
        embedding,
    }))
}

async fn graph_refresh_status(
    State(state): State<AppState>,
) -> Json<schematic_mcp::GraphRefreshOutcome> {
    Json(schematic_mcp::graph_refresh_status(state.project.as_path()).await)
}

async fn embedding_status(State(state): State<AppState>) -> Json<EmbeddingOutcome> {
    Json(state.embedding_status.read().await.clone())
}

async fn schedule_embedding(state: &AppState, relative: String, body: String) -> EmbeddingOutcome {
    if body.trim().is_empty() {
        state.embedding_jobs.lock().await.remove(&relative);
        let current = EmbeddingOutcome {
            status: "current".into(),
            path: Some(relative),
            body_hash: Some(embedding_document::body_hash(&body)),
            diagnostic: None,
        };
        *state.embedding_status.write().await = current.clone();
        return current;
    }
    let generation = state.embedding_generation.fetch_add(1, Ordering::SeqCst) + 1;
    state
        .embedding_jobs
        .lock()
        .await
        .insert(relative.clone(), generation);
    let body_hash = embedding_document::body_hash(&body);
    let queued = EmbeddingOutcome {
        status: "queued".into(),
        path: Some(relative.clone()),
        body_hash: Some(body_hash.clone()),
        diagnostic: None,
    };
    *state.embedding_status.write().await = queued.clone();
    let worker = state.clone();
    tokio::spawn(async move {
        let Ok(_permit) = worker.embedding_slots.clone().acquire_owned().await else {
            return;
        };
        if worker.embedding_jobs.lock().await.get(&relative).copied() != Some(generation) {
            return;
        }
        *worker.embedding_status.write().await = EmbeddingOutcome {
            status: "processing".into(),
            path: Some(relative.clone()),
            body_hash: Some(body_hash.clone()),
            diagnostic: None,
        };
        let project = worker.project.as_ref().clone();
        let owner = match markdown_owner(worker.schematics.as_path(), &relative) {
            Ok(value) => value,
            Err(error) => {
                *worker.embedding_status.write().await = EmbeddingOutcome {
                    status: "failed".into(),
                    path: Some(relative),
                    body_hash: Some(body_hash),
                    diagnostic: Some(error.to_string()),
                };
                return;
            }
        };
        let body_for_derivation = body.clone();
        let derived = tokio::task::spawn_blocking(move || {
            schematic_graph::derive_embedding_envelope(
                &project,
                &owner,
                &body_for_derivation,
                &schematic_graph::LoadOptions::default(),
            )
        })
        .await;
        let outcome = match derived {
            Ok(Ok(envelope)) => {
                publish_embedding_header(&worker, &relative, generation, &body, &envelope).await
            }
            Ok(Err(error)) => Err(error),
            Err(error) => Err(Error::Message(format!("embedding task failed: {error}"))),
        };
        match outcome {
            Ok(true) => {
                *worker.embedding_status.write().await = EmbeddingOutcome {
                    status: "current".into(),
                    path: Some(relative),
                    body_hash: Some(body_hash),
                    diagnostic: None,
                };
            }
            Ok(false) => {}
            Err(error) => {
                worker.embedding_jobs.lock().await.remove(&relative);
                *worker.embedding_status.write().await = EmbeddingOutcome {
                    status: "failed".into(),
                    path: Some(relative),
                    body_hash: Some(body_hash),
                    diagnostic: Some(error.to_string()),
                };
            }
        }
    });
    queued
}

async fn schedule_project_embeddings(state: &AppState) -> Result<usize> {
    let documents = WalkDir::new(state.schematics.as_path())
        .follow_links(false)
        .into_iter()
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            entry.file_type().is_file()
                && entry.path().extension().and_then(|value| value.to_str()) == Some("md")
        })
        .map(|entry| entry.path().to_path_buf())
        .collect::<Vec<_>>();
    let mut scheduled = 0;
    for path in documents {
        let physical = tokio::fs::read_to_string(&path).await?;
        let parsed = embedding_document::parse_markdown(&physical);
        if parsed.body.trim().is_empty() {
            continue;
        }
        let relative = path
            .strip_prefix(state.schematics.as_path())
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/");
        let current = parsed.envelope.as_ref().is_some_and(|envelope| {
            envelope.body_hash == embedding_document::body_hash(&parsed.body)
                && envelope.model == schematic_graph::EMBEDDING_MODEL
                && embedding_document::validate_envelope_shape(envelope).is_ok()
        });
        if !current {
            schedule_embedding(state, relative, parsed.body).await;
            scheduled += 1;
        }
    }
    Ok(scheduled)
}

pub async fn backfill_embeddings(project: impl AsRef<Path>) -> Result<usize> {
    let state = AppState::new(project)?;
    let scheduled = schedule_project_embeddings(&state).await?;
    while !state.embedding_jobs.lock().await.is_empty() {
        tokio::time::sleep(std::time::Duration::from_millis(25)).await;
    }
    let status = state.embedding_status.read().await.clone();
    if status.status == "failed" {
        return Err(Error::Message(
            status
                .diagnostic
                .unwrap_or_else(|| "embedding backfill failed".into()),
        ));
    }
    Ok(scheduled)
}

async fn publish_embedding_header(
    state: &AppState,
    relative: &str,
    generation: u64,
    expected_body: &str,
    envelope: &embedding_document::EmbeddingEnvelope,
) -> Result<bool> {
    if state.embedding_jobs.lock().await.get(relative).copied() != Some(generation) {
        return Ok(false);
    }
    let path = state.resolve(relative, false)?;
    let current = tokio::fs::read_to_string(&path).await?;
    let parsed = embedding_document::parse_markdown(&current);
    if parsed.body != expected_body
        || envelope.body_hash != embedding_document::body_hash(&parsed.body)
    {
        return Ok(false);
    }
    let physical = embedding_document::serialize_markdown(envelope, &parsed.body)?;
    if physical != current {
        atomic_write(&path, physical.as_bytes()).await?;
    }
    state.embedding_jobs.lock().await.remove(relative);
    let _ = schematic_mcp::notify_documents_changed(
        state.project.as_path(),
        relative,
        schematic_mcp::DocumentChangeKind::Replaced,
    )
    .await;
    Ok(true)
}

fn markdown_owner(schematics: &Path, relative: &str) -> Result<String> {
    let relative_path = Path::new(relative);
    if relative_path.extension().and_then(|value| value.to_str()) != Some("md") {
        return Err(Error::Message("embedding source must be Markdown".into()));
    }
    let file = relative_path
        .file_name()
        .and_then(|value| value.to_str())
        .unwrap_or("");
    let (diagram_folder, suffix) = if file == "main.md" {
        (
            relative_path.parent().unwrap_or(Path::new("")),
            "diagram".to_owned(),
        )
    } else if relative_path
        .parent()
        .and_then(Path::file_name)
        .and_then(|value| value.to_str())
        == Some("docs")
    {
        (
            relative_path
                .parent()
                .and_then(Path::parent)
                .unwrap_or(Path::new("")),
            relative_path
                .file_stem()
                .and_then(|value| value.to_str())
                .unwrap_or("")
                .to_owned(),
        )
    } else {
        return Err(Error::Message(
            "Markdown is not connected to a schematic owner".into(),
        ));
    };
    let diagram = ["cmmn", "bpmn"]
        .iter()
        .map(|extension| diagram_folder.join(format!("main.{extension}")))
        .find(|candidate| schematics.join(candidate).is_file())
        .ok_or_else(|| Error::Message("Markdown owner diagram does not exist".into()))?;
    Ok(format!(
        "{}#{suffix}",
        diagram.to_string_lossy().replace('\\', "/")
    ))
}

async fn atomic_write(path: &Path, content: &[u8]) -> Result<()> {
    let file_name = path
        .file_name()
        .and_then(|x| x.to_str())
        .ok_or_else(|| Error::Message("invalid filename".into()))?;
    let temporary = path.with_file_name(format!(".{file_name}.{}.tmp", std::process::id()));
    tokio::fs::write(&temporary, content).await?;
    #[cfg(windows)]
    if path.exists() {
        tokio::fs::remove_file(path).await?;
    }
    tokio::fs::rename(temporary, path).await?;
    Ok(())
}

async fn rename_documentation(
    State(state): State<AppState>,
    Json(request): Json<RenameRequest>,
) -> Result<StatusCode> {
    validate_id(&request.old_id)?;
    validate_id(&request.new_id)?;
    let diagram = state.resolve(&request.diagram_path, false)?;
    let folder = diagram
        .parent()
        .ok_or_else(|| Error::Message("diagram has no composition folder".into()))?;
    let old = folder.join("docs").join(format!("{}.md", request.old_id));
    let new = folder.join("docs").join(format!("{}.md", request.new_id));
    if new.exists() {
        return Err(Error::Message("documentation target already exists".into()));
    }
    if old.exists() {
        tokio::fs::rename(&old, &new).await?;
        let relative = new
            .strip_prefix(state.schematics.as_path())
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/");
        let physical = tokio::fs::read_to_string(&new).await?;
        let body = embedding_document::parse_markdown(&physical).body;
        atomic_write(&new, body.as_bytes()).await?;
        schedule_embedding(&state, relative.clone(), body).await;
        let _ = schematic_mcp::notify_documents_changed(
            state.project.as_path(),
            &relative,
            schematic_mcp::DocumentChangeKind::Renamed,
        )
        .await;
    }
    Ok(StatusCode::NO_CONTENT)
}

fn validate_id(id: &str) -> Result<()> {
    if id.is_empty()
        || !id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '-'))
    {
        return Err(Error::Message(
            "element ID must contain only letters, digits, underscore, or hyphen".into(),
        ));
    }
    Ok(())
}

async fn resolve_composition(
    State(state): State<AppState>,
    Json(request): Json<CompositionRequest>,
) -> Result<Json<CompositionResponse>> {
    let (name, relative_folder, extension, starter) =
        match request.kind.as_str() {
            "bpmn" => {
                let name = request.qualified_name.as_deref().ok_or_else(|| {
                    Error::Message("BPMN composition requires qualified_name".into())
                })?;
                let folder = composition_folder_for_name(name)?
                    .to_string_lossy()
                    .replace('\\', "/");
                (
                    name.to_owned(),
                    folder,
                    "bpmn",
                    set_definitions_process_name(STARTER_BPMN, name),
                )
            }
            "cmmn" => {
                let name = request.package_name.as_deref().ok_or_else(|| {
                    Error::Message("CMMN composition requires package_name".into())
                })?;
                validate_package_name(name)?;
                let folder = name
                    .split('.')
                    .collect::<PathBuf>()
                    .to_string_lossy()
                    .replace('\\', "/");
                (
                    name.to_owned(),
                    folder,
                    "cmmn",
                    set_definitions_package_name(STARTER_CMMN, name),
                )
            }
            _ => {
                return Err(Error::Message(
                    "composition kind must be bpmn or cmmn".into(),
                ));
            }
        };
    let folder = state.resolve(&relative_folder, true)?;
    let diagram = folder.join(format!("main.{extension}"));
    let documentation = folder.join("main.md");
    let created = !diagram.exists();
    if created {
        tokio::fs::create_dir_all(&folder).await?;
        atomic_write(&diagram, starter.as_bytes()).await?;
        if !documentation.exists() {
            atomic_write(&documentation, STARTER_MD.as_bytes()).await?;
        }
        let relative_diagram = diagram
            .strip_prefix(state.schematics.as_path())
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/");
        let _ = schematic_mcp::notify_documents_changed(
            state.project.as_path(),
            &relative_diagram,
            schematic_mcp::DocumentChangeKind::Created,
        )
        .await;
    }
    let relative = |path: &Path| {
        path.strip_prefix(state.schematics.as_path())
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/")
    };
    Ok(Json(CompositionResponse {
        name,
        diagram: relative(&diagram),
        documentation: relative(&documentation),
        created,
    }))
}

async fn rename_package(
    State(state): State<AppState>,
    Json(request): Json<PackageRenameRequest>,
) -> Result<StatusCode> {
    validate_package_name(&request.old_package_name)?;
    validate_package_name(&request.new_package_name)?;
    let old_folder = request.old_package_name.replace('.', "/");
    let new_folder = request.new_package_name.replace('.', "/");
    let old = state.resolve(&old_folder, false)?;
    let new = state.resolve(&new_folder, true)?;
    if new.exists() {
        return Err(Error::Message("package Name already exists".into()));
    }
    if !old.join("main.cmmn").exists() {
        return Err(Error::Message(
            "source package has no main.cmmn business anchor".into(),
        ));
    }
    if let Some(parent) = new.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::rename(&old, &new)?;
    rewrite_local_names(
        state.schematics.as_path(),
        &request.old_package_name,
        &request.new_package_name,
    )?;
    let renamed = format!("{new_folder}/main.cmmn");
    let _ = schematic_mcp::notify_documents_changed(
        state.project.as_path(),
        &renamed,
        schematic_mcp::DocumentChangeKind::Renamed,
    )
    .await;
    Ok(StatusCode::NO_CONTENT)
}

fn rewrite_local_names(root: &Path, old_name: &str, new_name: &str) -> Result<()> {
    for entry in WalkDir::new(root).follow_links(false) {
        let entry = entry?;
        if entry.file_type().is_file()
            && entry
                .path()
                .extension()
                .is_some_and(|x| x.eq_ignore_ascii_case("bpmn") || x.eq_ignore_ascii_case("cmmn"))
        {
            let content = fs::read_to_string(entry.path())?;
            let rewritten = content.replace(old_name, new_name);
            if rewritten != content {
                fs::write(entry.path(), rewritten)?;
            }
        }
    }
    Ok(())
}

async fn rename_process(
    State(state): State<AppState>,
    Json(request): Json<ProcessRenameRequest>,
) -> Result<StatusCode> {
    validate_qualified_process_name(&request.old_qualified_name)?;
    validate_qualified_process_name(&request.new_qualified_name)?;
    let old_folder = composition_folder_for_name(&request.old_qualified_name)?
        .to_string_lossy()
        .replace('\\', "/");
    let new_folder = composition_folder_for_name(&request.new_qualified_name)?
        .to_string_lossy()
        .replace('\\', "/");
    let old = state.resolve(&old_folder, false)?;
    let new = state.resolve(&new_folder, true)?;
    if new.exists() {
        return Err(Error::Message("process Name already exists".into()));
    }
    if let Some(parent) = new.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::rename(&old, &new)?;
    rewrite_local_names(
        state.schematics.as_path(),
        &request.old_qualified_name,
        &request.new_qualified_name,
    )?;
    let renamed = format!("{new_folder}/main.bpmn");
    let _ = schematic_mcp::notify_documents_changed(
        state.project.as_path(),
        &renamed,
        schematic_mcp::DocumentChangeKind::Renamed,
    )
    .await;
    Ok(StatusCode::NO_CONTENT)
}

fn set_definitions_process_name(xml: &str, qualified_name: &str) -> String {
    if let Some(start) = xml.find("<bpmn:definitions")
        && let Some(end_offset) = xml[start..].find('>')
    {
        let end = start + end_offset;
        let tag = &xml[start..end];
        if tag.contains("ssw:processName=\"") {
            let marker = "ssw:processName=\"";
            let value_start = start + tag.find(marker).unwrap() + marker.len();
            if let Some(value_end) = xml[value_start..].find('"') {
                let mut result = xml.to_owned();
                result.replace_range(value_start..value_start + value_end, qualified_name);
                return result;
            }
        }
        let namespace = if tag.contains("xmlns:ssw=") {
            ""
        } else {
            " xmlns:ssw=\"https://software-schematic.dev/schema/bpmn\""
        };
        let mut result = xml.to_owned();
        result.insert_str(
            end,
            &format!("{namespace} ssw:processName=\"{qualified_name}\""),
        );
        return result;
    }
    xml.to_owned()
}

fn set_definitions_package_name(xml: &str, package_name: &str) -> String {
    if let Some(start) = xml.find("<cmmn:definitions")
        && let Some(end_offset) = xml[start..].find('>')
    {
        let end = start + end_offset;
        let tag = &xml[start..end];
        let namespace = if tag.contains("xmlns:ssw=") {
            ""
        } else {
            " xmlns:ssw=\"https://software-schematic.dev/schema/cmmn\""
        };
        let attribute = format!(" ssw:packageName=\"{package_name}\"");
        let mut result = xml.to_owned();
        result.insert_str(end, &format!("{namespace}{attribute}"));
        return result;
    }
    xml.to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::{
        body::{Body, to_bytes},
        http::{Request, StatusCode},
    };
    use tempfile::tempdir;
    use tower::ServiceExt;

    fn initialized() -> (tempfile::TempDir, ProjectLayout) {
        let directory = tempdir().unwrap();
        let layout = init_project(directory.path()).unwrap();
        (directory, layout)
    }

    #[test]
    fn scoped_names_validate_resolve_and_map_to_portable_folders() {
        assert_eq!(
            validate_package_name("cybling.subscription").unwrap(),
            "cybling.subscription"
        );
        assert_eq!(
            validate_process_name("SelectAndOutfit").unwrap(),
            "SelectAndOutfit"
        );
        assert_eq!(
            validate_member_name("outfitCybling").unwrap(),
            "outfitCybling"
        );
        assert!(validate_package_name("Cybling.subscription").is_err());
        assert!(validate_process_name("selectAndOutfit").is_err());
        assert!(validate_member_name("OutfitCybling").is_err());
        assert_eq!(
            validate_element_name("cybling.subscription.SelectAndOutfit#outfitCybling").unwrap(),
            "cybling.subscription.SelectAndOutfit#outfitCybling"
        );
        assert_eq!(
            validate_element_name("cybling.subscription.SelectAndOutfit").unwrap(),
            "cybling.subscription.SelectAndOutfit"
        );
        assert!(validate_element_name("SelectAndOutfit#outfitCybling").is_err());
        let folder = composition_folder_for_name("cybling.subscription.SelectAndOutfit").unwrap();
        assert_eq!(
            folder,
            PathBuf::from("cybling/subscription/SelectAndOutfit")
        );
        assert_eq!(
            qualified_name_for_composition_folder(&folder).unwrap(),
            "cybling.subscription.SelectAndOutfit"
        );
        assert_eq!(
            symbol_collision_key("ConfigureSubscription"),
            symbol_collision_key("configuresubscription")
        );
        assert!(qualified_name_for_composition_folder(Path::new("../private/Process")).is_err());
    }

    #[test]
    fn initialization_writes_complete_versioned_layout_and_refuses_collisions() {
        let (directory, layout) = initialized();
        assert!(layout.tool.join("web/index.html").is_file());
        assert!(layout.tool.join("operation-plan.schema.json").is_file());
        assert!(layout.tool.join("starter.cmmn").is_file());
        assert_eq!(
            fs::read_to_string(layout.tool.join("LICENSE")).unwrap(),
            PROJECT_LICENSE
        );
        assert_eq!(
            fs::read_to_string(layout.tool.join("NOTICE")).unwrap(),
            PROJECT_NOTICE
        );
        assert_eq!(
            fs::read_to_string(layout.tool.join("THIRD_PARTY_NOTICES.md")).unwrap(),
            THIRD_PARTY_NOTICES
        );
        assert!(layout.tool.join("web/vendor").is_dir());
        assert!(layout.schematics.join("main.cmmn").is_file());
        assert!(!layout.schematics.join("main.bpmn").exists());
        assert!(layout.schematics.join("main.md").is_file());
        assert_eq!(
            fs::read_to_string(layout.tool.join("version")).unwrap(),
            format!("{}\n", env!("CARGO_PKG_VERSION"))
        );
        assert!(directory.path().join("ssw.cmd").is_file());
        assert!(directory.path().join(".ss/project-id").is_file());
        assert!(
            fs::read_to_string(directory.path().join("AGENTS.md"))
                .unwrap()
                .contains("resolve the request's natural language")
        );
        let codex = fs::read_to_string(directory.path().join(".codex/config.toml")).unwrap();
        assert!(codex.contains("software_schematic"));
        assert!(codex.contains("command = \"./ssw\""));
        assert!(
            fs::read_to_string(directory.path().join("ssw"))
                .unwrap()
                .contains("auth --project")
        );
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_ne!(
                fs::metadata(directory.path().join("ssw"))
                    .unwrap()
                    .permissions()
                    .mode()
                    & 0o111,
                0
            );
        }
        assert!(
            init_project(directory.path())
                .unwrap_err()
                .to_string()
                .contains("already exists")
        );
    }

    #[test]
    fn update_preserves_authored_files_and_is_idempotent_with_crlf() {
        let (directory, layout) = initialized();
        let diagram_before = fs::read(layout.schematics.join("main.cmmn")).unwrap();
        fs::write(layout.tool.join("NOTICE"), "stale managed notice").unwrap();
        fs::write(directory.path().join("AGENTS.md"), "authored\r\n\r\n<!-- software-schematic:begin -->\r\nstale\r\n<!-- software-schematic:end -->\r\ntail\r\n").unwrap();
        fs::write(directory.path().join(".codex/config.toml"), "theme = \"dark\"\n\n[mcp_servers.other]\ncommand = \"other\"\n\n[mcp_servers.software_schematic]\ncommand = \"stale\"\n").unwrap();
        update_project(directory.path()).unwrap();
        let once_agents = fs::read(directory.path().join("AGENTS.md")).unwrap();
        let once_codex = fs::read(directory.path().join(".codex/config.toml")).unwrap();
        update_project(directory.path()).unwrap();
        assert_eq!(
            once_agents,
            fs::read(directory.path().join("AGENTS.md")).unwrap()
        );
        assert_eq!(
            once_codex,
            fs::read(directory.path().join(".codex/config.toml")).unwrap()
        );
        assert!(once_agents.starts_with(b"authored\r\n"));
        assert!(
            String::from_utf8(once_agents)
                .unwrap()
                .ends_with("tail\r\n")
        );
        let once_codex = String::from_utf8(once_codex).unwrap();
        assert!(once_codex.contains("theme = \"dark\""));
        assert!(once_codex.contains("[mcp_servers.other]"));
        assert!(once_codex.contains("command = \"./ssw\""));
        assert_eq!(
            diagram_before,
            fs::read(layout.schematics.join("main.cmmn")).unwrap()
        );
        assert_eq!(
            fs::read_to_string(layout.tool.join("NOTICE")).unwrap(),
            PROJECT_NOTICE
        );
    }

    #[test]
    fn update_refuses_incomplete_managed_guidance_and_invalid_toml() {
        let (directory, _) = initialized();
        fs::write(
            directory.path().join("AGENTS.md"),
            "authored\n<!-- software-schematic:begin -->\nstale\n",
        )
        .unwrap();
        let before = fs::read(directory.path().join("AGENTS.md")).unwrap();
        assert!(
            update_project(directory.path())
                .unwrap_err()
                .to_string()
                .contains("incomplete")
        );
        assert_eq!(
            before,
            fs::read(directory.path().join("AGENTS.md")).unwrap()
        );

        fs::write(directory.path().join("AGENTS.md"), "authored\n").unwrap();
        fs::write(directory.path().join(".codex/config.toml"), "not = [valid").unwrap();
        assert!(
            update_project(directory.path())
                .unwrap_err()
                .to_string()
                .contains("invalid .codex/config.toml")
        );
        assert_eq!(
            fs::read_to_string(directory.path().join(".codex/config.toml")).unwrap(),
            "not = [valid"
        );
    }

    #[test]
    fn initialized_project_loads_the_packaged_embedding_model() {
        let (directory, layout) = initialized();
        assert!(
            layout
                .tool
                .join("models/all-MiniLM-L6-v2/all-MiniLM-L6-v2.onnx")
                .is_file()
        );
        assert!(
            layout
                .tool
                .join("models/all-MiniLM-L6-v2/tokenizer.json")
                .is_file()
        );
        let snapshot = crate::schematic_graph::load_schematic_graph(
            directory.path(),
            crate::schematic_graph::LoadOptions::default(),
        )
        .unwrap();
        assert_eq!(snapshot.summary.embedding_model, "all-MiniLM-L6-v2");
    }

    #[test]
    fn project_assistant_configuration_contains_only_the_provider_selection() {
        let (directory, _) = initialized();
        let path = directory.path().join(".ss/assistant.json");
        fs::write(&path, br#"{"provider":"codex"}"#).unwrap();
        assert_eq!(
            configured_assistant_provider(directory.path()).as_deref(),
            Some("codex")
        );
        let content = fs::read_to_string(path).unwrap();
        assert!(!content.to_ascii_lowercase().contains("token"));
        assert!(!content.to_ascii_lowercase().contains("password"));
    }

    #[test]
    fn confinement_rejects_traversal_absolute_and_symlink_escape() {
        let (directory, _) = initialized();
        let state = AppState::new(directory.path()).unwrap();
        assert!(state.resolve("../private.md", true).is_err());
        assert!(state.resolve("/private.md", true).is_err());
        assert!(state.resolve("docs/Task_1.md", true).is_ok());
        #[cfg(unix)]
        {
            std::os::unix::fs::symlink(
                directory.path().parent().unwrap(),
                directory.path().join("schematics/link"),
            )
            .unwrap();
            assert!(state.resolve("link/secret.md", true).is_err());
        }
    }

    async fn send(
        router: Router,
        method: &str,
        uri: &str,
        body: Option<serde_json::Value>,
    ) -> (StatusCode, Vec<u8>) {
        let mut builder = Request::builder().method(method).uri(uri);
        let request_body = if let Some(value) = body {
            builder = builder.header("content-type", "application/json");
            Body::from(value.to_string())
        } else {
            Body::empty()
        };
        let response = router
            .oneshot(builder.body(request_body).unwrap())
            .await
            .unwrap();
        let status = response.status();
        let bytes = to_bytes(response.into_body(), 2 * 1024 * 1024)
            .await
            .unwrap()
            .to_vec();
        (status, bytes)
    }

    #[tokio::test]
    async fn typed_file_endpoints_replace_complete_content_and_list_diagrams() {
        let (directory, _) = initialized();
        let router = app(AppState::new(directory.path()).unwrap());
        let (status, bytes) = send(
            router.clone(),
            "PUT",
            "/api/file",
            Some(serde_json::json!({
                "path": "docs/Task_1.md", "content": "complete documentation", "revision": 7
            })),
        )
        .await;
        assert_eq!(status, StatusCode::OK);
        let response: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
        assert_eq!(response["path"], "docs/Task_1.md");
        assert_eq!(response["revision"], 7);
        assert_eq!(response["graphRefresh"]["status"], "notRunning");
        let (status, bytes) = send(
            router.clone(),
            "GET",
            "/api/file?path=docs%2FTask_1.md",
            None,
        )
        .await;
        assert_eq!(status, StatusCode::OK);
        assert_eq!(bytes, b"complete documentation");
        let (status, bytes) = send(router.clone(), "GET", "/api/diagrams", None).await;
        assert_eq!(status, StatusCode::OK);
        assert!(String::from_utf8(bytes).unwrap().contains("main.cmmn"));
        let (status, bytes) = send(router, "GET", "/api/graph-refresh", None).await;
        assert_eq!(status, StatusCode::OK);
        let response: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
        assert_eq!(response["status"], "notRunning");
    }

    #[tokio::test]
    async fn embedding_header_publication_is_compare_and_swap_and_hidden_from_ui() {
        let (directory, layout) = initialized();
        let state = AppState::new(directory.path()).unwrap();
        let path = layout.schematics.join("main.md");
        let old_body = "# Old body\n";
        let newer_body = "# Newer body\n";
        atomic_write(&path, newer_body.as_bytes()).await.unwrap();
        let envelope = schematic_graph::derive_embedding_envelope(
            directory.path(),
            "main.cmmn#diagram",
            old_body,
            &schematic_graph::LoadOptions::deterministic_test(),
        )
        .unwrap();
        state
            .embedding_jobs
            .lock()
            .await
            .insert("main.md".into(), 1);
        assert!(
            !publish_embedding_header(&state, "main.md", 1, old_body, &envelope)
                .await
                .unwrap()
        );
        assert_eq!(fs::read_to_string(&path).unwrap(), newer_body);

        let envelope = schematic_graph::derive_embedding_envelope(
            directory.path(),
            "main.cmmn#diagram",
            newer_body,
            &schematic_graph::LoadOptions::deterministic_test(),
        )
        .unwrap();
        state
            .embedding_jobs
            .lock()
            .await
            .insert("main.md".into(), 2);
        assert!(
            publish_embedding_header(&state, "main.md", 2, newer_body, &envelope)
                .await
                .unwrap()
        );
        assert!(
            fs::read_to_string(&path)
                .unwrap()
                .starts_with(embedding_document::HEADER_START)
        );
        let (status, bytes) = send(app(state), "GET", "/api/file?path=main.md", None).await;
        assert_eq!(status, StatusCode::OK);
        assert_eq!(bytes, newer_body.as_bytes());
    }

    #[tokio::test]
    async fn successful_web_save_refreshes_running_mcp_revision() {
        let (directory, _) = initialized();
        let server = schematic_mcp::SchematicMcp::load(
            directory.path(),
            schematic_graph::LoadOptions::deterministic_test(),
        )
        .unwrap();
        let initial = server.summary().await.revision;
        let _listener = schematic_mcp::start_refresh_listener(server.clone())
            .await
            .unwrap();
        let router = app(AppState::new(directory.path()).unwrap());
        let (status, bytes) = send(
            router,
            "PUT",
            "/api/file",
            Some(serde_json::json!({
                "path": "main.md",
                "content": "# Evaluated contract\nA required parameter was added by the user.",
                "revision": 1
            })),
        )
        .await;
        assert_eq!(status, StatusCode::OK);
        let response: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
        assert_eq!(response["graphRefresh"]["status"], "queued");
        let active = tokio::time::timeout(std::time::Duration::from_secs(5), async {
            loop {
                let status = schematic_mcp::graph_refresh_status(directory.path()).await;
                if !matches!(
                    status.status,
                    schematic_mcp::GraphRefreshStatus::Queued
                        | schematic_mcp::GraphRefreshStatus::Processing
                ) {
                    break status.active_revision.unwrap();
                }
                tokio::task::yield_now().await;
            }
        })
        .await
        .unwrap();
        assert_ne!(active, initial);
        assert_eq!(server.summary().await.revision, active);
        assert_eq!(
            fs::read_to_string(directory.path().join("schematics/main.md")).unwrap(),
            "# Evaluated contract\nA required parameter was added by the user."
        );
    }

    #[tokio::test]
    async fn project_metadata_returns_only_the_unicode_directory_basename() {
        let parent = tempdir().unwrap();
        let project = parent.path().join("Café Platform");
        init_project(&project).unwrap();
        fs::write(
            project.join(".ss/assistant.json"),
            br#"{"provider":"fake"}"#,
        )
        .unwrap();
        let router = app(AppState::new(&project).unwrap());
        let (status, bytes) = send(router, "GET", "/api/project", None).await;
        assert_eq!(status, StatusCode::OK);
        let metadata: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
        assert_eq!(
            metadata,
            serde_json::json!({ "name": "Café Platform", "assistant_provider": "fake" })
        );
        assert!(
            !String::from_utf8(bytes)
                .unwrap()
                .contains(&parent.path().to_string_lossy().to_string())
        );
    }

    #[tokio::test]
    async fn documentation_rename_refuses_collisions() {
        let (directory, _) = initialized();
        let docs = directory.path().join("schematics/docs");
        fs::create_dir_all(&docs).unwrap();
        fs::write(docs.join("Old.md"), "old").unwrap();
        fs::write(docs.join("Taken.md"), "taken").unwrap();
        let router = app(AppState::new(directory.path()).unwrap());
        let (status, _) = send(
            router,
            "POST",
            "/api/rename-documentation",
            Some(serde_json::json!({
                "diagram_path": "main.cmmn", "old_id": "Old", "new_id": "Taken"
            })),
        )
        .await;
        assert_eq!(status, StatusCode::BAD_REQUEST);
        assert_eq!(fs::read_to_string(docs.join("Old.md")).unwrap(), "old");
        assert_eq!(fs::read_to_string(docs.join("Taken.md")).unwrap(), "taken");
    }

    #[tokio::test]
    async fn documentation_rename_follows_id_and_not_architectural_name() {
        let (directory, _) = initialized();
        let docs = directory.path().join("schematics/docs");
        fs::create_dir_all(&docs).unwrap();
        fs::write(docs.join("Activity_42.md"), "call-site documentation").unwrap();
        let router = app(AppState::new(directory.path()).unwrap());
        let (status, _) = send(
            router,
            "POST",
            "/api/rename-documentation",
            Some(serde_json::json!({
                "diagram_path": "main.cmmn", "old_id": "Activity_42", "new_id": "Activity_99"
            })),
        )
        .await;
        assert_eq!(status, StatusCode::NO_CONTENT);
        assert!(!docs.join("Activity_42.md").exists());
        assert_eq!(
            fs::read_to_string(docs.join("Activity_99.md")).unwrap(),
            "call-site documentation"
        );
        assert!(!docs.join("validateOrder.md").exists());
    }

    #[tokio::test]
    async fn composition_creation_is_idempotent_and_reusable() {
        let (directory, _) = initialized();
        let router = app(AppState::new(directory.path()).unwrap());
        let payload = serde_json::json!({ "qualified_name": "sales.Order" });
        let (first_status, first) = send(
            router.clone(),
            "POST",
            "/api/compositions",
            Some(payload.clone()),
        )
        .await;
        let (second_status, second) =
            send(router, "POST", "/api/compositions", Some(payload)).await;
        assert_eq!(first_status, StatusCode::OK);
        assert_eq!(second_status, StatusCode::OK);
        assert!(
            String::from_utf8(first)
                .unwrap()
                .contains("\"created\":true")
        );
        assert!(
            String::from_utf8(second)
                .unwrap()
                .contains("\"created\":false")
        );
        assert!(
            directory
                .path()
                .join("schematics/sales/Order/main.bpmn")
                .is_file()
        );
        assert!(
            directory
                .path()
                .join("schematics/sales/Order/main.md")
                .is_file()
        );
        let diagram =
            fs::read_to_string(directory.path().join("schematics/sales/Order/main.bpmn")).unwrap();
        assert!(!diagram.contains("<bpmn:startEvent"));
        assert!(!diagram.contains("<bpmn:task"));
        assert!(!diagram.contains("<bpmn:sequenceFlow"));
        assert!(!diagram.contains("<bpmndi:BPMNShape"));
    }

    #[tokio::test]
    async fn cmmn_business_anchor_coexists_with_descendant_bpmn_and_renames_confined_package() {
        let (directory, _) = initialized();
        let router = app(AppState::new(directory.path()).unwrap());
        let anchor = serde_json::json!({ "kind": "cmmn", "package_name": "cybling" });
        let (status, bytes) = send(router.clone(), "POST", "/api/compositions", Some(anchor)).await;
        assert_eq!(status, StatusCode::OK);
        assert!(
            String::from_utf8(bytes)
                .unwrap()
                .contains("cybling/main.cmmn")
        );
        let design = serde_json::json!({ "kind": "bpmn", "qualified_name": "cybling.sdk.Birth" });
        let (status, _) = send(router.clone(), "POST", "/api/compositions", Some(design)).await;
        assert_eq!(status, StatusCode::OK);
        assert!(
            directory
                .path()
                .join("schematics/cybling/main.cmmn")
                .is_file()
        );
        assert!(
            directory
                .path()
                .join("schematics/cybling/sdk/Birth/main.bpmn")
                .is_file()
        );
        assert!(
            !directory
                .path()
                .join("schematics/cybling/sdk/main.cmmn")
                .exists()
        );
        let cmmn =
            fs::read_to_string(directory.path().join("schematics/cybling/main.cmmn")).unwrap();
        assert!(cmmn.contains("ssw:packageName=\"cybling\""));
        let (status, bytes) = send(router.clone(), "GET", "/api/diagrams", None).await;
        assert_eq!(status, StatusCode::OK);
        let listed = String::from_utf8(bytes).unwrap();
        assert!(listed.contains("cybling/main.cmmn"));
        assert!(listed.contains("cybling/sdk/Birth/main.bpmn"));
        let rename =
            serde_json::json!({ "old_package_name": "cybling", "new_package_name": "platform" });
        let (status, _) = send(router, "POST", "/api/package-renames", Some(rename)).await;
        assert_eq!(status, StatusCode::NO_CONTENT);
        assert!(
            directory
                .path()
                .join("schematics/platform/main.cmmn")
                .is_file()
        );
        assert!(
            directory
                .path()
                .join("schematics/platform/sdk/Birth/main.bpmn")
                .is_file()
        );
        assert!(!directory.path().join("schematics/cybling").exists());
    }

    #[tokio::test]
    async fn process_rename_moves_folder_and_updates_shared_references() {
        let (directory, _) = initialized();
        let state = AppState::new(directory.path()).unwrap();
        let router = app(state);
        let create =
            serde_json::json!({ "qualified_name": "cybling.subscription.SelectAndOutfit" });
        let (status, _) = send(router.clone(), "POST", "/api/compositions", Some(create)).await;
        assert_eq!(status, StatusCode::OK);
        let old = directory
            .path()
            .join("schematics/cybling/subscription/SelectAndOutfit");
        fs::create_dir_all(old.join("assets")).unwrap();
        fs::write(old.join("assets/model.png"), b"portable").unwrap();
        fs::write(old.join("main.md"), "![model](./assets/model.png)").unwrap();
        let root = directory.path().join("schematics/main.cmmn");
        fs::write(&root, fs::read_to_string(&root).unwrap().replace("<cmmn:case", "<cmmn:process id=\"Process_Reference\" externalRef=\"cybling.subscription.SelectAndOutfit\" /><cmmn:case")).unwrap();
        let rename = serde_json::json!({ "old_qualified_name": "cybling.subscription.SelectAndOutfit", "new_qualified_name": "cybling.subscription.ConfigureSubscription" });
        let (rename_status, _) = send(router, "POST", "/api/process-renames", Some(rename)).await;
        assert_eq!(rename_status, StatusCode::NO_CONTENT);
        let new = directory
            .path()
            .join("schematics/cybling/subscription/ConfigureSubscription");
        assert!(!old.exists());
        assert_eq!(fs::read(new.join("assets/model.png")).unwrap(), b"portable");
        assert_eq!(
            fs::read_to_string(new.join("main.md")).unwrap(),
            "![model](./assets/model.png)"
        );
        assert!(
            fs::read_to_string(root)
                .unwrap()
                .contains("externalRef=\"cybling.subscription.ConfigureSubscription\"")
        );
        assert!(
            fs::read_to_string(new.join("main.bpmn"))
                .unwrap()
                .contains("ssw:processName=\"cybling.subscription.ConfigureSubscription\"")
        );
    }

    #[tokio::test]
    async fn process_rename_rejects_existing_name() {
        let (directory, _) = initialized();
        let router = app(AppState::new(directory.path()).unwrap());
        for name in ["sales.Order", "sales.Invoice"] {
            let (status, _) = send(
                router.clone(),
                "POST",
                "/api/compositions",
                Some(serde_json::json!({ "qualified_name": name })),
            )
            .await;
            assert_eq!(status, StatusCode::OK);
        }
        let (collision, _) = send(router, "POST", "/api/process-renames", Some(serde_json::json!({ "old_qualified_name": "sales.Order", "new_qualified_name": "sales.Invoice" }))).await;
        assert_eq!(collision, StatusCode::BAD_REQUEST);
    }

    #[tokio::test]
    async fn assistant_endpoint_returns_a_correlated_non_mutating_fake_proposal() {
        let (directory, _) = initialized();
        fs::create_dir_all(directory.path().join(".ss")).unwrap();
        fs::write(
            directory.path().join(".ss/assistant.json"),
            br#"{"provider":"fake"}"#,
        )
        .unwrap();
        let before = fs::read_to_string(directory.path().join("schematics/main.cmmn")).unwrap();
        let router = app(AppState::new(directory.path()).unwrap());
        let (status, bytes) = send(router, "POST", "/api/assistant/proposals", Some(serde_json::json!({
            "requestId": "request-1", "prompt": "Improve this task", "snapshot": {
                "version": "2.0", "diagramPath": "main.cmmn", "sourceRevision": "revision-1", "primaryNodeId": "Task_1",
                "graph": {"nodes": [{"id": "Task_1", "name": "work", "label": "Work", "status": "open"}], "flows": []}
            }
        }))).await;
        assert_eq!(status, StatusCode::OK);
        let result: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
        assert_eq!(result["proposal"]["requestId"], "request-1");
        assert_eq!(result["provider"], "fake");
        assert_eq!(
            fs::read_to_string(directory.path().join("schematics/main.cmmn")).unwrap(),
            before
        );
    }
}
