use axum::{
    Json, Router,
    extract::{Query, State},
    http::StatusCode,
    response::{IntoResponse, Response},
    routing::{get, post},
};
use include_dir::{Dir, include_dir};
use serde::{Deserialize, Serialize};
use std::{
    fs,
    path::{Component, Path, PathBuf},
    sync::Arc,
};
use thiserror::Error;
use tower_http::services::{ServeDir, ServeFile};
use walkdir::WalkDir;

// Release builds embed the production web bundle generated by software-schematic-web.
static WEB_ASSETS: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/assets/web");
const STARTER_BPMN: &str = include_str!("../assets/starter.bpmn");
const STARTER_MD: &str = include_str!("../assets/starter.md");
const MAC_WRAPPER: &str = "#!/bin/sh\nset -eu\nSCRIPT_DIR=$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\nexec \"$SCRIPT_DIR/.ss/bin/ss\" serve --project \"$SCRIPT_DIR\" \"$@\"\n";
const WINDOWS_WRAPPER: &str =
    "@echo off\r\nsetlocal\r\n\"%~dp0.ss\\bin\\ss.exe\" serve --project \"%~dp0\" %*\r\n";

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Debug, Error)]
pub enum Error {
    #[error("{0}")]
    Message(String),
    #[error(transparent)]
    Io(#[from] std::io::Error),
    #[error(transparent)]
    WalkDir(#[from] walkdir::Error),
}

impl IntoResponse for Error {
    fn into_response(self) -> Response {
        let status = match self {
            Error::Message(_) => StatusCode::BAD_REQUEST,
            Error::Io(ref value) if value.kind() == std::io::ErrorKind::NotFound => {
                StatusCode::NOT_FOUND
            }
            _ => StatusCode::INTERNAL_SERVER_ERROR,
        };
        (
            status,
            Json(serde_json::json!({ "error": self.to_string() })),
        )
            .into_response()
    }
}

#[derive(Debug, Clone)]
pub struct ProjectLayout {
    pub project: PathBuf,
    pub tool: PathBuf,
    pub schematics: PathBuf,
}

pub fn init_project(project: impl AsRef<Path>) -> Result<ProjectLayout> {
    let project = absolute(project.as_ref())?;
    fs::create_dir_all(&project)?;
    let collisions: Vec<_> = [".ss", "schematics", "ssw", "ssw.cmd"]
        .into_iter()
        .map(|name| project.join(name))
        .filter(|path| path.exists())
        .collect();
    if !collisions.is_empty() {
        return Err(Error::Message(format!(
            "initialization refused; path already exists: {}",
            collisions
                .iter()
                .map(|p| p.display().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        )));
    }

    let tool = project.join(".ss");
    let web = tool.join("web");
    let schematics = project.join("schematics");
    fs::create_dir_all(tool.join("bin"))?;
    fs::create_dir_all(&web)?;
    fs::create_dir_all(&schematics)?;
    WEB_ASSETS
        .extract(&web)
        .map_err(|e| Error::Message(e.to_string()))?;
    fs::write(
        tool.join("version"),
        format!("{}\n", env!("CARGO_PKG_VERSION")),
    )?;
    fs::write(schematics.join("main.bpmn"), STARTER_BPMN)?;
    fs::write(schematics.join("main.md"), STARTER_MD)?;
    fs::write(project.join("ssw"), MAC_WRAPPER)?;
    fs::write(project.join("ssw.cmd"), WINDOWS_WRAPPER)?;

    let current_exe = std::env::current_exe()?;
    let runtime_name = if cfg!(windows) { "ss.exe" } else { "ss" };
    fs::copy(current_exe, tool.join("bin").join(runtime_name))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(project.join("ssw"), fs::Permissions::from_mode(0o755))?;
        fs::set_permissions(
            tool.join("bin").join(runtime_name),
            fs::Permissions::from_mode(0o755),
        )?;
    }
    Ok(ProjectLayout {
        project,
        tool,
        schematics,
    })
}

fn absolute(path: &Path) -> Result<PathBuf> {
    if path.is_absolute() {
        Ok(path.to_path_buf())
    } else {
        Ok(std::env::current_dir()?.join(path))
    }
}

#[derive(Clone)]
pub struct AppState {
    project: Arc<PathBuf>,
    schematics: Arc<PathBuf>,
}

impl AppState {
    pub fn new(project: impl AsRef<Path>) -> Result<Self> {
        let project = absolute(project.as_ref())?.canonicalize()?;
        let schematics = project.join("schematics").canonicalize()?;
        Ok(Self {
            project: Arc::new(project),
            schematics: Arc::new(schematics),
        })
    }

    pub fn resolve(&self, relative: &str, permit_missing: bool) -> Result<PathBuf> {
        let path = Path::new(relative);
        if relative.is_empty()
            || path.is_absolute()
            || path
                .components()
                .any(|c| !matches!(c, Component::Normal(_)))
        {
            return Err(Error::Message(
                "path must be a normalized path relative to schematics".into(),
            ));
        }
        let candidate = self.schematics.join(path);
        let mut existing = candidate.as_path();
        while !existing.exists() {
            existing = existing
                .parent()
                .ok_or_else(|| Error::Message("path has no confined ancestor".into()))?;
        }
        let canonical_ancestor = existing.canonicalize()?;
        if !canonical_ancestor.starts_with(self.schematics.as_path()) {
            return Err(Error::Message("path escapes schematics".into()));
        }
        if !permit_missing && !candidate.exists() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                format!("{} not found", relative),
            )
            .into());
        }
        if candidate.exists()
            && !candidate
                .canonicalize()?
                .starts_with(self.schematics.as_path())
        {
            return Err(Error::Message("path escapes schematics".into()));
        }
        Ok(candidate)
    }

    pub fn project_name(&self) -> Result<String> {
        self.project
            .file_name()
            .and_then(|value| value.to_str())
            .filter(|value| !value.is_empty())
            .map(str::to_owned)
            .ok_or_else(|| Error::Message("project directory has no usable name".into()))
    }
}

#[derive(Deserialize)]
struct PathQuery {
    path: String,
}

#[derive(Deserialize)]
struct WriteRequest {
    path: String,
    content: String,
    revision: u64,
}

#[derive(Serialize)]
struct WriteResponse {
    path: String,
    revision: u64,
}

#[derive(Deserialize)]
struct RenameRequest {
    diagram_path: String,
    old_id: String,
    new_id: String,
}

#[derive(Deserialize)]
struct CompositionRequest {
    path: String,
}

#[derive(Serialize)]
struct CompositionResponse {
    diagram: String,
    documentation: String,
    created: bool,
}

#[derive(Serialize)]
struct ProjectMetadata {
    name: String,
}

pub fn app(state: AppState) -> Router {
    let web = state.project.join(".ss/web");
    Router::new()
        .route("/api/project", get(project_metadata))
        .route("/api/diagrams", get(list_diagrams))
        .route("/api/file", get(read_file).put(write_file))
        .route("/api/rename-documentation", post(rename_documentation))
        .route("/api/compositions", post(resolve_composition))
        .fallback_service(
            ServeDir::new(&web).not_found_service(ServeFile::new(web.join("index.html"))),
        )
        .with_state(state)
}

async fn project_metadata(State(state): State<AppState>) -> Result<Json<ProjectMetadata>> {
    Ok(Json(ProjectMetadata {
        name: state.project_name()?,
    }))
}

pub async fn serve(project: PathBuf, open_browser: bool) -> Result<()> {
    let state = AppState::new(project)?;
    let listener = tokio::net::TcpListener::bind((std::net::Ipv4Addr::LOCALHOST, 0)).await?;
    let address = listener.local_addr()?;
    let url = format!("http://{address}");
    println!("Software Schematic is running at {url}");
    if open_browser {
        open::that(&url).map_err(|e| Error::Message(format!("could not open browser: {e}")))?;
    }
    axum::serve(listener, app(state))
        .with_graceful_shutdown(shutdown_signal())
        .await?;
    Ok(())
}

async fn shutdown_signal() {
    let ctrl_c = async {
        tokio::signal::ctrl_c()
            .await
            .expect("install Ctrl+C handler")
    };
    #[cfg(unix)]
    let terminate = async {
        tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
            .expect("install signal handler")
            .recv()
            .await;
    };
    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();
    tokio::select! { _ = ctrl_c => {}, _ = terminate => {} }
}

async fn list_diagrams(State(state): State<AppState>) -> Result<Json<Vec<String>>> {
    let mut diagrams = Vec::new();
    for entry in WalkDir::new(state.schematics.as_path()).follow_links(false) {
        let entry = entry?;
        if entry.file_type().is_file()
            && entry
                .path()
                .extension()
                .is_some_and(|ext| ext.eq_ignore_ascii_case("bpmn"))
        {
            diagrams.push(
                entry
                    .path()
                    .strip_prefix(state.schematics.as_path())
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/"),
            );
        }
    }
    diagrams.sort();
    Ok(Json(diagrams))
}

async fn read_file(
    State(state): State<AppState>,
    Query(query): Query<PathQuery>,
) -> Result<String> {
    let path = state.resolve(&query.path, false)?;
    if !matches!(
        path.extension().and_then(|x| x.to_str()),
        Some("bpmn" | "md")
    ) {
        return Err(Error::Message(
            "only BPMN and Markdown files are readable".into(),
        ));
    }
    Ok(tokio::fs::read_to_string(path).await?)
}

async fn write_file(
    State(state): State<AppState>,
    Json(request): Json<WriteRequest>,
) -> Result<Json<WriteResponse>> {
    let path = state.resolve(&request.path, true)?;
    if !matches!(
        path.extension().and_then(|x| x.to_str()),
        Some("bpmn" | "md")
    ) {
        return Err(Error::Message(
            "only BPMN and Markdown files are writable".into(),
        ));
    }
    if let Some(parent) = path.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }
    atomic_write(&path, request.content.as_bytes()).await?;
    Ok(Json(WriteResponse {
        path: request.path,
        revision: request.revision,
    }))
}

async fn atomic_write(path: &Path, content: &[u8]) -> Result<()> {
    let file_name = path
        .file_name()
        .and_then(|x| x.to_str())
        .ok_or_else(|| Error::Message("invalid filename".into()))?;
    let temporary = path.with_file_name(format!(".{file_name}.{}.tmp", std::process::id()));
    tokio::fs::write(&temporary, content).await?;
    #[cfg(windows)]
    if path.exists() {
        tokio::fs::remove_file(path).await?;
    }
    tokio::fs::rename(temporary, path).await?;
    Ok(())
}

async fn rename_documentation(
    State(state): State<AppState>,
    Json(request): Json<RenameRequest>,
) -> Result<StatusCode> {
    validate_id(&request.old_id)?;
    validate_id(&request.new_id)?;
    let diagram = state.resolve(&request.diagram_path, false)?;
    let folder = diagram
        .parent()
        .ok_or_else(|| Error::Message("diagram has no composition folder".into()))?;
    let old = folder.join("docs").join(format!("{}.md", request.old_id));
    let new = folder.join("docs").join(format!("{}.md", request.new_id));
    if new.exists() {
        return Err(Error::Message("documentation target already exists".into()));
    }
    if old.exists() {
        tokio::fs::rename(old, new).await?;
    }
    Ok(StatusCode::NO_CONTENT)
}

fn validate_id(id: &str) -> Result<()> {
    if id.is_empty()
        || !id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '-'))
    {
        return Err(Error::Message(
            "element ID must contain only letters, digits, underscore, or hyphen".into(),
        ));
    }
    Ok(())
}

async fn resolve_composition(
    State(state): State<AppState>,
    Json(request): Json<CompositionRequest>,
) -> Result<Json<CompositionResponse>> {
    let folder = state.resolve(&request.path, true)?;
    if folder.extension().is_some() {
        return Err(Error::Message(
            "composition path must identify a folder".into(),
        ));
    }
    let diagram = folder.join("main.bpmn");
    let documentation = folder.join("main.md");
    let created = !folder.exists();
    if created {
        tokio::fs::create_dir_all(&folder).await?;
        atomic_write(&diagram, STARTER_BPMN.as_bytes()).await?;
        atomic_write(&documentation, STARTER_MD.as_bytes()).await?;
    }
    let relative = |path: &Path| {
        path.strip_prefix(state.schematics.as_path())
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/")
    };
    Ok(Json(CompositionResponse {
        diagram: relative(&diagram),
        documentation: relative(&documentation),
        created,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::{
        body::{Body, to_bytes},
        http::{Request, StatusCode},
    };
    use tempfile::tempdir;
    use tower::ServiceExt;

    fn initialized() -> (tempfile::TempDir, ProjectLayout) {
        let directory = tempdir().unwrap();
        let layout = init_project(directory.path()).unwrap();
        (directory, layout)
    }

    #[test]
    fn initialization_writes_complete_versioned_layout_and_refuses_collisions() {
        let (directory, layout) = initialized();
        assert!(layout.tool.join("web/index.html").is_file());
        assert!(layout.tool.join("web/vendor").is_dir());
        assert!(layout.schematics.join("main.bpmn").is_file());
        assert!(layout.schematics.join("main.md").is_file());
        assert_eq!(
            fs::read_to_string(layout.tool.join("version")).unwrap(),
            format!("{}\n", env!("CARGO_PKG_VERSION"))
        );
        assert!(directory.path().join("ssw.cmd").is_file());
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_ne!(
                fs::metadata(directory.path().join("ssw"))
                    .unwrap()
                    .permissions()
                    .mode()
                    & 0o111,
                0
            );
        }
        assert!(
            init_project(directory.path())
                .unwrap_err()
                .to_string()
                .contains("already exists")
        );
    }

    #[test]
    fn confinement_rejects_traversal_absolute_and_symlink_escape() {
        let (directory, _) = initialized();
        let state = AppState::new(directory.path()).unwrap();
        assert!(state.resolve("../private.md", true).is_err());
        assert!(state.resolve("/private.md", true).is_err());
        assert!(state.resolve("docs/Task_1.md", true).is_ok());
        #[cfg(unix)]
        {
            std::os::unix::fs::symlink(
                directory.path().parent().unwrap(),
                directory.path().join("schematics/link"),
            )
            .unwrap();
            assert!(state.resolve("link/secret.md", true).is_err());
        }
    }

    async fn send(
        router: Router,
        method: &str,
        uri: &str,
        body: Option<serde_json::Value>,
    ) -> (StatusCode, Vec<u8>) {
        let mut builder = Request::builder().method(method).uri(uri);
        let request_body = if let Some(value) = body {
            builder = builder.header("content-type", "application/json");
            Body::from(value.to_string())
        } else {
            Body::empty()
        };
        let response = router
            .oneshot(builder.body(request_body).unwrap())
            .await
            .unwrap();
        let status = response.status();
        let bytes = to_bytes(response.into_body(), 2 * 1024 * 1024)
            .await
            .unwrap()
            .to_vec();
        (status, bytes)
    }

    #[tokio::test]
    async fn typed_file_endpoints_replace_complete_content_and_list_diagrams() {
        let (directory, _) = initialized();
        let router = app(AppState::new(directory.path()).unwrap());
        let (status, _) = send(
            router.clone(),
            "PUT",
            "/api/file",
            Some(serde_json::json!({
                "path": "docs/Task_1.md", "content": "complete documentation", "revision": 7
            })),
        )
        .await;
        assert_eq!(status, StatusCode::OK);
        let (status, bytes) = send(
            router.clone(),
            "GET",
            "/api/file?path=docs%2FTask_1.md",
            None,
        )
        .await;
        assert_eq!(status, StatusCode::OK);
        assert_eq!(bytes, b"complete documentation");
        let (status, bytes) = send(router, "GET", "/api/diagrams", None).await;
        assert_eq!(status, StatusCode::OK);
        assert!(String::from_utf8(bytes).unwrap().contains("main.bpmn"));
    }

    #[tokio::test]
    async fn project_metadata_returns_only_the_unicode_directory_basename() {
        let parent = tempdir().unwrap();
        let project = parent.path().join("Café Platform");
        init_project(&project).unwrap();
        let router = app(AppState::new(&project).unwrap());
        let (status, bytes) = send(router, "GET", "/api/project", None).await;
        assert_eq!(status, StatusCode::OK);
        let metadata: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
        assert_eq!(metadata, serde_json::json!({ "name": "Café Platform" }));
        assert!(!String::from_utf8(bytes).unwrap().contains(&parent.path().to_string_lossy().to_string()));
    }

    #[tokio::test]
    async fn documentation_rename_refuses_collisions() {
        let (directory, _) = initialized();
        let docs = directory.path().join("schematics/docs");
        fs::create_dir_all(&docs).unwrap();
        fs::write(docs.join("Old.md"), "old").unwrap();
        fs::write(docs.join("Taken.md"), "taken").unwrap();
        let router = app(AppState::new(directory.path()).unwrap());
        let (status, _) = send(
            router,
            "POST",
            "/api/rename-documentation",
            Some(serde_json::json!({
                "diagram_path": "main.bpmn", "old_id": "Old", "new_id": "Taken"
            })),
        )
        .await;
        assert_eq!(status, StatusCode::BAD_REQUEST);
        assert_eq!(fs::read_to_string(docs.join("Old.md")).unwrap(), "old");
        assert_eq!(fs::read_to_string(docs.join("Taken.md")).unwrap(), "taken");
    }

    #[tokio::test]
    async fn composition_creation_is_idempotent_and_reusable() {
        let (directory, _) = initialized();
        let router = app(AppState::new(directory.path()).unwrap());
        let payload = serde_json::json!({ "path": "order" });
        let (first_status, first) = send(
            router.clone(),
            "POST",
            "/api/compositions",
            Some(payload.clone()),
        )
        .await;
        let (second_status, second) =
            send(router, "POST", "/api/compositions", Some(payload)).await;
        assert_eq!(first_status, StatusCode::OK);
        assert_eq!(second_status, StatusCode::OK);
        assert!(
            String::from_utf8(first)
                .unwrap()
                .contains("\"created\":true")
        );
        assert!(
            String::from_utf8(second)
                .unwrap()
                .contains("\"created\":false")
        );
        assert!(
            directory
                .path()
                .join("schematics/order/main.bpmn")
                .is_file()
        );
        assert!(directory.path().join("schematics/order/main.md").is_file());
    }
}
